In [ ]:
## 1. Split this string

In [26]:
s = "splitting a string"

In [27]:
print(s.split())

['splitting', 'a', 'string']


In [3]:
## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [39]:
planet = "Jupyter"
diameter = 142984

In [41]:
print("The diameter of {planet} is {distance} kilometeres".format(planet="Earth",distance=142984))


The diameter of Earth is 142984 kilometeres


In [42]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hey there!']}]}]}


In [43]:
print(d['k1'][3]['tricky'][3]['target'][3])


hey there!


In [31]:
import numpy as np


In [32]:
## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [33]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
np.ones(10)*5


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [35]:
## 5. Create an array of all the even integers from 20 to 35

In [37]:
array=np.arange(21,38,2)
print(array)

[21 23 25 27 29 31 33 35 37]


In [38]:
## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [44]:
array1=np.arange(0,9).reshape(3,3)
print(array1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [45]:
## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [46]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c=np.concatenate((a,b),axis=0)
print(c)

[1 2 3 4 5 6]


In [20]:
# Pandas
## 8. Create a dataframe with 3 rows and 2 columns

In [47]:
import pandas as pd
data=[["logeshwaran",1],["bharath",2],["vj",3],["yash",4],["jag",5]]
data1=pd.DataFrame(data,columns=["name","age"])
print(data1)

          name  age
0  logeshwaran    1
1      bharath    2
2           vj    3
3         yash    4
4          jag    5


In [48]:
## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [49]:
data4=pd.date_range(start="1-01-2023",end="10-02-2023",freq="5h")
print(data4)

DatetimeIndex(['2023-01-01 00:00:00', '2023-01-01 05:00:00',
               '2023-01-01 10:00:00', '2023-01-01 15:00:00',
               '2023-01-01 20:00:00', '2023-01-02 01:00:00',
               '2023-01-02 06:00:00', '2023-01-02 11:00:00',
               '2023-01-02 16:00:00', '2023-01-02 21:00:00',
               ...
               '2023-09-30 02:00:00', '2023-09-30 07:00:00',
               '2023-09-30 12:00:00', '2023-09-30 17:00:00',
               '2023-09-30 22:00:00', '2023-10-01 03:00:00',
               '2023-10-01 08:00:00', '2023-10-01 13:00:00',
               '2023-10-01 18:00:00', '2023-10-01 23:00:00'],
              dtype='datetime64[ns]', length=1316, freq='5H')


In [50]:
## 10. Create 2D list to DataFrame

lists = [[1, 'logesh', 22],
         [2, 'waran', 25],
         [3, 'bahbg', 24]]

In [51]:
data2=pd.DataFrame(lists,columns=["s.no","Name","marks"])
print(data2)

   s.no    Name  marks
0     1  logesh     22
1     2   waran     25
2     3   bahbg     24
